### ISSUE TITLE
Detailed HTML results is not showing full expanse of test data

### ISSUE THREAD

**Issue by gokusupa** [essenius/FitNesseRun#12]
It seems that the detailed HTML report is not longer giving all the details. Prior to the recent changes the entire fitnesse pages would be shown in detail for each and every test, showing what failed and why. Tests that passed were even shown in 100% detail. Now the are only displaying the name of the test and no other test data.

Below is and example of what is shown currently
![image](https://user-images.githubusercontent.com/26933360/82547190-b32c1400-9b2f-11ea-973a-91538454319b.png)

One of our tests was shown correctly but it seems the rest were ignored. Regardless if they passed or failed.

**Comment by essenius** [comment]
My own suite tests all run fine and give the right detailed reports, so it seems you ran into some kind of edge case. Can you check the fitnesse.xml file that was created? If that has the same (lack of) data, then the FitNesse run itself is the culprit. If it seems correct, then the transformation is going wrong somewhere.

**Comment by gokusupa** [comment]
I just checked and it does have the same lack of data in that fitnesse.xml file.

**Comment by gokusupa** [comment]
Moving forward. I went ahead and took my suite and split it up into two smaller suites. I executed the task against each of them and the issue did not appear. IT was only when combined into a larger suite is this issue occuring.

I'm going to try and get you a suite I can provide for you where the issue occurs for me.

**Comment by gokusupa** [comment]
This can be closed as a mistake on my part. The fitnesse server was being started via another powershell cmd before the "fitnesserun" task would execute. Once removed this issue went away.
