### ISSUE TITLE
Invalid XML results

### ISSUE THREAD

**Issue by mlsomers** [essenius/FitNesseRun#4]
The tests are running, but the output xml seems to be jumbled:

```
[error]Cannot convert value "<?xml version="1.0"?>
// 5000 lines of xml output
</testResults>" to type "System.Xml.XmlDocument". Error: "The 'evaluationMessage' start tag on line 649 position 42 does not match the end tag of 'expectation'.
```

I tried to manually fix the output in Notepad++ but there are many of these errors. Tags seem to be overlapping each other.

I don't know what exactly happens but the symptoms look like the output is written to a stack by one thread, and another thread is reading it from there. The reading thread is usually fast enough so there is only one line on the stack, but not always…
Or something similar (it sometimes breaks between lines).

Here's an example where : `</expectation>` and `</instructionResult>` are swapped:
```
<instructionResult>
	<instruction>{id='decisionTable_0_109', instruction='call', instanceName='decisionTable_0', methodName='KortingInc', args=[]}</instruction>
	<slimResult>pass(41,18)</slimResult>
	<expectation>
		<status>pass</status>
		<instructionId>decisionTable_0_109</instructionId>
		<col>4</col>
		<row>12</row>
		<type>ReturnedValueExpectation</type>
		<evaluationMessage>41,18</evaluationMessage>
	</instructionResult>
</expectation>
```
Here part of the content was split:
```
<instructionResult>
	<instruction>{id='decisionTable_0_71', instruction='call', instanceName='decisionTable_0', methodName='KortingOmscrijving', args=[]}</instruction>
	<slimResult>19,50</slimResult>
	<expectation>
		<status>ignore</status>
		<instructionId>decisionTable_0_71</instructionId>
		<col>6</col>
		<row>8</row>
		<type>ReturnedValueExpectation</type>
		<evaluationMessage>19,5
		</expectation>
0</evaluationMessage>
</instructionResult>
```

I'm not sure if it's Fitnesse or TFS causing this?

**Comment by mlsomers** [comment]
Digging deeper I think it must be a Fitnesse or FitSharp or SLIM issue.
I've opened a ticket here:
https://github.com/unclebob/fitnesse/issues/1242

**Comment by mlsomers** [comment]
I got the same output xml by running the test in my browser while adding this to the URL: `&format=xml&nochunk&includehtml`

After saving it to a file I could determine that it is valid XML.

To check the rest of the process, I took your FitNesseRun.ps1 script and changed the last part of the script to this:

```
######## Start of script ########
## if (TestOnAgent) { InvokeMainTask } else { Exit-WithError -Message "Not running on an agent. Exiting." }

$content = ${C:\full path\FitnesseOutput.xml}
$transformed = ExtractXmlOrHtml -RawInput $content;
$transformed | Out-File "C:\full path\result.xml"
SaveXml -xml $transformed -OutFile "C:\full path\result2.xml"
```
After running `FitNesseRun.ps1` both `result.xml` as well as `result2.xml` are valid...
I'm running out of ideas right now...

**Comment by mlsomers** [comment]
I reverted to setting up a Coninually running fitnesse service using NSSM on the build server (this will have to be done on every agent).
Now I get correct output.
I consider this a workaround. Has anyone got it working with the setup and Run method?

**Comment by waltairodu** [comment]
@mlsomers , 

Need your assistance here. We are trying to integrate FitNesseRun task in AzureDevOps with Build Agent (Onprem). 

Throwing error: 
While triggering the build. Getting the below error:

"
Could not find an XML or HTML section in the result. Raw result: Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
"

Any assistance would be of much help

-Yogi

**Comment by essenius** [comment]
@YogiBabaji without a bit more context it's hard to analyze that. It looks like FitNesse got triggered, but didn't return test results. I'd suggest to run the FitNesse command manually to see what gets back.

**Comment by essenius** [comment]
@mlsomers the Call method uses the REST API (which seems a bit more stable option for integration) and the Execute method reads the output stream from the FitNesse process. Indeed it looks like there is some kind of timing related issue with that. Did you get any further in the meantime?

**Comment by gokusupa** [comment]
I have run into the exact same issue. The issue happens about 5% of our test runs, so most of the time its a non issue. But every now and again the XML is malformed resulting in this error and no tests published.

Considering workarounds now, have not heard of NSSM and might look in that direction.

**Comment by essenius** [comment]
@mlsomers I've uploaded a new version of FitNesseRun (1.0.32)  to the market place that no longer asks FitNesse to include HTML content in the raw results if the "Include HTML" flag is off. I hope this helps fixing your issue, or at least reducing its frequency. It should make the fitnesse.xml files a lot smaller so the likelihood of such issues should get smaller too.

**Comment by essenius** [comment]
@mlsomers See also https://github.com/essenius/FitNesseRun/issues/8#issuecomment-627131749. It's quite likely you ran into the same issue.
