### ISSUE TITLE
Suite gets run as if it were a test

### ISSUE THREAD

**Issue by mlsomers** [essenius/FitNesseRun#5]
There is an undocumented prerequisite to run a suite.
The name must either start or end with "suite" otherwise it will be run with "?test" (and fails).

Please add a checkbox so we can explicitly run it as a test or suite.

Hope I don't sound to negative opening these issues... I'm glad with your extension! Though it was a rough ride, it would have been even more rough without your plugin. Thanks!

**Comment by tcnh** [comment]
You can append `:suite` to your page path. It will run it as a suite.

**Comment by essenius** [comment]
@mlsomers thanks for the feedback.
