### ISSUE TITLE
Publish Results fails with "AutomatedTestName must be specified"

### ISSUE THREAD

**Issue by tdunnington** [essenius/FitNesseRun#6]
I am running a test suite with the FitNesseRun add on, using an existing fitnesse host. After running the test, the publish step fails, and I see no test results in DevOps. We're on Azure DevOps on prem. The tests run on the host Fitnesse server, and we are getting test results in the results file on the build agent.

Here is the fitnesse step YAML:
```
steps:
- task: rikessenius.FitnesseRun.fitnesse-run-task.FitNesseRun@1
  displayName: 'Run Fitnesse Test Suite'
  inputs:
    testSpec: FrontPage.FhirTestSuite.DocumentReferenceTestSuite
    includeHtml: false
    baseUri: 'http://our.host.name:8888/'
  continueOnError: true
```

And right after that is the publish step YAML:
```
steps:
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '.\results_nunit.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'FrontPage.FhirTestSuite.DocumentReferenceTestSuite-Run'
```

Here is the log showing the result of the publish results:
```
...
2019-11-07T21:24:14.3135095Z [command]E:\Agents\01\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\2.153.5\modules\TestResultsPublisher.exe @E:\Agents\01\_work\_temp\f2815d10-01a4-11ea-9935-49cc6bb012b0.txt
2019-11-07T21:24:15.7672611Z No build level attachments to publish.
2019-11-07T21:24:16.3303887Z    at Microsoft.VisualStudio.Services.WebApi.
... full stack trace ...
2019-11-07T21:24:16.7597432Z Publishing test results to test run '3384'.
2019-11-07T21:24:16.7630387Z TestResults To Publish 8, Test run id:3384
2019-11-07T21:24:16.7706824Z Test results publishing 8, remaining: 0. Test run id: 3384
2019-11-07T21:24:16.9222394Z ##[warning]Failed to publish test results: AutomatedTestName must be specified for automated test runs when neither TestPointId nor TestCaseId has been specified..
2019-11-07T21:24:16.9586965Z ##[error]There are one or more test failures detected in result files. Detailed summary of published test results can be viewed in the Tests tab.
2019-11-07T21:24:17.0588102Z ##[section]Finishing: Publish Test Results
```

**Comment by tcnh** [comment]
Also experiencing this on Azure DevOps. Have you found any way to fix this? I tried adding an AutomatedTestName element to the nunit output, but couldn't build/test the extension using VS2019CE?

**Comment by tdunnington** [comment]
@tcnh I tried similar things but nothing seems to work. 

I wish I understood what Azure DevOps is really asking for. Is it asking for a missing element/attribute in the XML? If so, does that element data have to match up with something in DevOps? Or does it want a new argument to the REST call that posts this result into DevOps? 

I've done some hunting around to see if I can figure this out, but the documentation isn't clear. Frustrating!

**Comment by essenius** [comment]
@tdunnington @tcnh if you have some data for me to reproduce I'm happy to have a look.

**Comment by essenius** [comment]
I was able to reproduce the issue. Indeed apparently Azure DevOps has changed something in the expectations for the NUnit format. I'll have a look over the next couple of days.

**Comment by tdunnington** [comment]
@essenius I'd be happy to get whatever you need to help with this. I put some snippets of configurations up in my original post. Let me know what else you need and I'll gladly get it for you.

Also, I'd be happy to contribute a PR to the project if I just knew what it was that Azure DevOps was wanting. The error doesn't quite make it clear what it wants. So even if you could tell me what Azure DevOps needs, I could put in a PR and help contribute.

Here's the specific error it's complaining about:

`##[warning]Failed to publish test results: AutomatedTestName must be specified for automated test runs when neither TestPointId nor TestCaseId has been specified..`

**Comment by essenius** [comment]
The files results_nunit.xml (this is the input for the publish task) and fitnesse.xml (the raw output of FitNesse) would be useful.

**Comment by tdunnington** [comment]
Hey Rik, thank you. I’ll grab those files during the day today (it’s just barely 6am here this morning) and get back to you.

Tim

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tdunnington** [comment]
Hey Rick, here are the files you requested.

Thanks again for your help!
Tim

________________________________

**Comment by gokusupa** [comment]
Had the same problem here.  When I populated the "Test run title" of the "Publish Test Results" this problem occured, removing it did resolbe my issue.

![image](https://user-images.githubusercontent.com/26933360/73384655-e39e2880-4288-11ea-8afc-15f02ac7966f.png)

**Comment by tdunnington** [comment]
@gokusupa thanks for the suggestion but this didn't help me. Not sure why, but I'm getting the exact same result as I did before.

**Comment by essenius** [comment]
@tdunnington I think I figured out what went wrong. When a (Suite)Setup page was used that wasn't in the root folder of the suite being executed (e.g. in the parent page), then its name was resolved to an empty string, hence the message complaining that no name was specified. I corrected the transformation, and uploaded version 1.0.20 to the marketplace. Can you try if this fixes your issue?

**Comment by tdunnington** [comment]
@essenius I just got the plugin updated and tested it...it's working! Thank you sir!
